[package]
name = "w8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rzdb = { path = "../rzdb" }
sfml = "0.16.0"
rand = "0.8.4"
simdnoise = "3.1.6"

[profile.release]
debug = true